version: '3'

services:
  web:
    restart: always
    build: ./cryptocoin
    expose:
      - "8000"
    links:
      - postgres:postgres
      # - redis:redis
    volumes:
      - web-django:/code
      - web-static:/code/cryptocoin/static
      - web-media:/code/cryptocoin/media
    # env_file: .env
    environment:
      - DEBUG='True'
      - RUN_IN_DOCKER='True'
    command: /usr/local/bin/gunicorn cryptocoin.wsgi:application -w 2 -b :8000

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
    volumes:
      - web-static:/code/cryptocoin/static
      - web-media:/code/cryptocoin/media
    links:
      - web:web

  postgres:
    restart: always
    image: postgres:latest
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  # redis:
  #   restart: always
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redisdata:/data

volumes:
  web-django:
  web-static:
  web-media:
  pgdata:
  # redisdata:
